//go:build ignore

// gen_models.go 从 OpenRouter API 拉全量模型，生成编译期基线 models_generated.go。
// 用法: go generate ./internal/models/...
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	openRouterURL = "https://openrouter.ai/api/v1/models"
	// maxModelAgeDays 决定基线中保留多老的模型。超过这个年龄视作已过时（GPT-3.5、
	// 原版 GPT-4、Llama 2、Mistral 7b 等），直接剔除以减小二进制体积和查询噪声。
	// 同 pricing.go 的运行期过滤保持一致。
	maxModelAgeDays = 730
)

// 与 pricing.go 保持一致。
var providerMap = map[string]string{
	"anthropic":  "anthropic",
	"openai":     "openai",
	"google":     "gemini",
	"deepseek":   "deepseek",
	"qwen":       "qwen",
	"x-ai":       "grok",
	"z-ai":       "glm",
	"meta-llama": "meta-llama",
	"mistralai":  "mistral",
	"moonshotai": "moonshot",
	"xiaomi":     "mimo",
	"minimax":    "minimax",
}

type apiResponse struct {
	Data []apiModel `json:"data"`
}

type apiModel struct {
	ID            string       `json:"id"`
	Name          string       `json:"name"`
	ContextLength int          `json:"context_length"`
	Created       int64        `json:"created"`
	Pricing       *apiPricing  `json:"pricing"`
	TopProvider   *apiProvider `json:"top_provider"`
}

type apiPricing struct {
	Prompt          string `json:"prompt"`
	Completion      string `json:"completion"`
	InputCacheRead  string `json:"input_cache_read"`
	InputCacheWrite string `json:"input_cache_write"`
}

type apiProvider struct {
	MaxCompletionTokens int `json:"max_completion_tokens"`
}

type entry struct {
	Provider            string
	ID                  string
	Name                string
	ContextWindow       int
	MaxTokens           int
	InputCostPer1M      float64
	OutputCostPer1M     float64
	CacheReadCostPer1M  float64
	CacheWriteCostPer1M float64
}

func main() {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(openRouterURL)
	if err != nil {
		log.Fatalf("fetch: %v", err)
	}
	defer resp.Body.Close()

	var result apiResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		log.Fatalf("decode: %v", err)
	}

	var entries []entry
	for _, m := range result.Data {
		e, ok := convert(m)
		if !ok {
			continue
		}
		entries = append(entries, e)
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Provider != entries[j].Provider {
			return entries[i].Provider < entries[j].Provider
		}
		return entries[i].ID < entries[j].ID
	})

	if err := writeFile(entries); err != nil {
		log.Fatalf("write: %v", err)
	}
	fmt.Printf("generated %d models\n", len(entries))
}

func convert(m apiModel) (entry, bool) {
	parts := strings.SplitN(m.ID, "/", 2)
	if len(parts) != 2 {
		return entry{}, false
	}
	prov, ok := providerMap[parts[0]]
	if !ok {
		return entry{}, false
	}
	modelID := parts[1]
	if strings.Contains(modelID, ":") {
		return entry{}, false
	}
	if isTooOld(m.Created) {
		return entry{}, false
	}

	e := entry{
		Provider:      prov,
		ID:            modelID,
		Name:          cleanName(m.Name),
		ContextWindow: m.ContextLength,
	}
	if m.TopProvider != nil {
		e.MaxTokens = m.TopProvider.MaxCompletionTokens
	}
	if m.Pricing != nil {
		e.InputCostPer1M = toMillion(m.Pricing.Prompt)
		e.OutputCostPer1M = toMillion(m.Pricing.Completion)
		e.CacheReadCostPer1M = toMillion(m.Pricing.InputCacheRead)
		e.CacheWriteCostPer1M = toMillion(m.Pricing.InputCacheWrite)
	}
	return e, true
}

// isTooOld 判断 created 时间戳是否超过 maxModelAgeDays。
// 0 或负值视为数据缺失，按"老模型"处理直接剔除。
func isTooOld(created int64) bool {
	if created <= 0 {
		return true
	}
	age := time.Since(time.Unix(created, 0)).Hours() / 24
	return age > maxModelAgeDays
}

func toMillion(s string) float64 {
	if s == "" {
		return 0
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0
	}
	return math.Round(v*1_000_000*1e6) / 1e6
}

func cleanName(name string) string {
	if _, after, ok := strings.Cut(name, ": "); ok {
		return after
	}
	return name
}

func writeFile(entries []entry) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Source: %s\n", openRouterURL)
	fmt.Fprintf(&sb, "// Generated: %s\n\n", time.Now().UTC().Format("2006-01-02"))
	sb.WriteString("package models\n\n")
	sb.WriteString("var generatedModels = []ModelEntry{\n")

	prev := ""
	for _, e := range entries {
		if e.Provider != prev {
			if prev != "" {
				sb.WriteString("\n")
			}
			fmt.Fprintf(&sb, "\t// %s\n", e.Provider)
			prev = e.Provider
		}
		fmt.Fprintf(&sb, "\t{Provider: %q, ID: %q, Name: %q, ContextWindow: %d, MaxTokens: %d",
			e.Provider, e.ID, e.Name, e.ContextWindow, e.MaxTokens)
		fmt.Fprintf(&sb, ", InputCostPer1M: %s, OutputCostPer1M: %s",
			formatFloat(e.InputCostPer1M), formatFloat(e.OutputCostPer1M))
		if e.CacheReadCostPer1M > 0 || e.CacheWriteCostPer1M > 0 {
			fmt.Fprintf(&sb, ", CacheReadCostPer1M: %s, CacheWriteCostPer1M: %s",
				formatFloat(e.CacheReadCostPer1M), formatFloat(e.CacheWriteCostPer1M))
		}
		sb.WriteString("},\n")
	}

	sb.WriteString("}\n")
	return os.WriteFile("models_generated.go", []byte(sb.String()), 0o644)
}

func formatFloat(f float64) string {
	if f == 0 {
		return "0"
	}
	s := strconv.FormatFloat(f, 'f', -1, 64)
	if !strings.Contains(s, ".") {
		s += ".0"
	}
	return s
}
